easy_admin:
    site_name: 'Julian Li'
    entities:
        # List the entity class name you want to manage
        - App\Entity\Education
        - App\Entity\Experience
        - App\Entity\Freelancer
        - App\Entity\Skill
        - App\Entity\SocialNetwork
        - App\Entity\Project
        - App\Entity\Post
