easy_admin:
    site_name: 'Julian Li'
    entities:
        # List the entity class name you want to manage
        Freelancer:
            class: App\Entity\Freelancer
        Education:
            class: App\Entity\Education
        Experience:
            class: App\Entity\Experience
        Skill:
            class: App\Entity\Skill
        SocialNetwork:
            class: App\Entity\SocialNetwork
        Project:
            class: App\Entity\Project
            list:
                fields: ['id', 'title', 'shortDescription', { property: 'coverImageUrl', type: 'image', base_path: '%app.path.projects%' }, { property: 'innerImageUrl', type: 'image', base_path: '%app.path.projects%'} 'tag']
            show:
                fields: [{ property: 'coverImageUrl', type: 'image', base_path: '%app.path.projects%' }, { property: 'innerImageUrl', type: 'image', base_path: '%app.path.projects%' }]
            form:
                fields: ['title', 'shortDescription', 'description', { property: 'coverImageFile', type: 'vich_image' }, { property: 'innerImageFile', type: 'vich_image' }, 'tag']
        Post:
            class: App\Entity\Post
            list:
                fields: ['id', 'title', 'slug', { property: 'coverImageUrl', type: 'image', base_path: '%app.path.posts%' }, 'tags']
            show:
                fields:
                    - { property: 'coverImageUrl', type: 'image', base_path: '%app.path.posts%' }
            form:
                fields: ['title', 'slug', 'content', { property: 'coverImageFile', type: 'vich_image' }, 'tags']
        Tag:
            class: App\Entity\Tag
