easy_admin:
    site_name: 'Julian Li'
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Education
#        - App\Entity\Experience
#        - App\Entity\Freelancer
#        - App\Entity\Skill
#        - App\Entity\SocialNetwork
#        - App\Entity\Project
        Post:
            class: App\Entity\Post
            list:
                fields:
                    - { property: 'coverImageUrl', type: 'image', base_path: '/img/uploads/blog/' }
            show:
                fields:
                    - { property: 'coverImageUrl', type: 'image', base_path: '/img/uploads/blog/' }
#        - App\Entity\Tag
