parameters:
    app.path.posts: img/uploads/blog
    app.path.projects: img/uploads/project

vich_uploader:
    db_driver: orm

    mappings:
        blogs:
            uri_prefix: '%app.path.posts%'
            upload_destination: '%kernel.project_dir%/public/%app.path.posts%'
        projects:
            uri_prefix: '%app.path.projects%'
            upload_destination: '%kernel.project_dir%/public/%app.path.projects%'

