parameters:
    app.path.posts: /img/uploads/blog/

vich_uploader:
    db_driver: orm

    mappings:
        blogs:
            uri_prefix: '%app.path.posts%'
            upload_destination: '%kernel.project_dir%/public/%app.path.posts%'
