---
- name: Install composer dependencies
  environment:
    APP_ENV: prod
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"

- name: Clear the cache
  command: "{{ release_console_path }} cache:clear --no-warmup --env=prod"

- name: Warm up the cache
  command: "{{ release_console_path }} cache:warmup --env=prod"

- name: Create DB if not exists
  command: "{{ release_console_path }} doctrine:database:create --if-not-exists --env=prod"
  register: create_db_output
  changed_when: not create_db_output.stdout|search('already exists. Skipped')

- name: Run migrations
  command: "{{ release_console_path }} doctrine:migrations:migrate --no-interaction --env=prod"
  register: run_migrations_output
  changed_when: not run_migrations_output.stdout|search('No migrations to execute')
